apiVersion: v1
kind: Service
metadata:
  name: aivid-cloud-master-health-monitor-script-service
  namespace: default
  labels:
    app: aivid-cloud-master-health-monitor-script
    app.kubernetes.io/name: aivid-health-monitoring-master-script
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: helm
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
  selector:
    app: aivid-cloud-master-health-monitor-script