kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: aivid-cloud-metricbeat-storage-database
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: aws-efs
  volumeMode: Filesystem