apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: aivid
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-10.7.2
  name: operations-portal-mongodb
  namespace: {{ .Values.global.namespace }}
data:
  mongodb-root-password: YWl2aWQxMjN2aXNpb24=
