kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redisdata
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: aws-efs
  volumeMode: Filesystem