apiVersion: v1
kind: Service
metadata:
  name: operations-portal-redis
  namespace: {{ .Values.global.namespace }}
  labels:
    app: operations-portal-redis
    app.kubernetes.io/name: redis
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: helm
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
  selector:
    app: operations-portal-redis
