apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: aivid-cloud-db
spec:
  serviceName: aivid-cloud-db
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: aivid-cloud-db
  template:
    metadata:
      labels:
        app: aivid-cloud-db
        database: 'yes'
    spec:
      imagePullSecrets:
        - name: {{ .Values.global.imagePullSecrets }}
      enableServiceLinks: true
      containers:
        - name: {{ .Chart.Name }}
          image: "aividtech/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 9200
            - containerPort: 9300
          env:
            - name: discovery.type
              value: single-node
            - name: NO_PROXY
              value: '*'
            - name: no_proxy
              value: '*'
            - name: ES_JAVA_OPTS
              value: '-Xms2g -Xmx2g'
            - name: path.repo
              value: /usr/share/elasticsearch/backup
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elasticdata
            - mountPath: /usr/share/elasticsearch/backup
              name: snapshot
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
      initContainers:
        - name: init-volume-sysctl
          image: aividtech/busybox:latest
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - '-c'
            - >-
              sysctl -w vm.max_map_count=262144 && ulimit -n 65535 && ulimit -u
              4096
          securityContext:
            privileged: true
        - image: aividtech/busybox:latest
          imagePullPolicy: IfNotPresent
          name: init
          command:
            - /bin/chown
            - '0:0'
            - /usr/share/elasticsearch/data
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elasticdata
      volumes:
        - name: elasticdata
          persistentVolumeClaim:
            claimName: aivid-cloud-storage-database
        - name: snapshot
          persistentVolumeClaim:
            claimName: aivid-cloud-snapshot-storage-database