kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: backend
  namespace: {{ .Values.global.namespace }}
spec:
  to:
    kind: Service
    name: operational-portal-backend-service
  port:
    targetPort: 32000
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect