apiVersion: v1
kind: Service
metadata:
  name: operations-portal-mongodb
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: aivid
    app.kubernetes.io/name: mongodb
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    name: mongodb
    targetPort: {{ .Values.service.targerPort }}
  selector:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: aivid
    app.kubernetes.io/name: mongodb
