apiVersion: v1
kind: Pod
metadata:
  name: bftest-httpserver
  labels:
    app: bftest-httpserver
spec:
  #nodeSelector:
  #  kubernetes.io/hostname: master3
  containers:
  - name: bftest-httpserver
    image: docker.io/manish2296lion/rootcontainer:latest
    command: ["/bin/bash", "-c", "(sleep 100000 &) && pscap"]
    automountServiceAccountToken: true
    securityContext:
      capabilities:
        add:
          - ALL
        runAsUser: 0
        runAsGroup: 0
