apiVersion: v1
kind: Service
metadata:
  name: aivid-node-office1-gateway-service
  namespace: default
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
  selector:
    app: aivid-node-office1-gateway
