apiVersion: apps/v1
kind: Deployment
metadata:
  name: aivid-node-office1-data-handler
  labels:
    app: aivid-node-office1-data-handler
    app.kubernetes.io/name: datahandler-node
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: helm
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: aivid-node-office1-data-handler
  template:
    metadata:
      labels:
        app: aivid-node-office1-data-handler
    spec:
      enableServiceLinks: false
      imagePullSecrets:
        - name: {{ .Values.global.imagePullSecrets }}
      containers:
        - name: {{ .Chart.Name }}
          image: "aividtech/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            limits:
              cpu: 50m
          env:
            - name: aivid_cloud
              value: 'false'
            - name: OFFICE
              value: 11.11,-22.22
            - name: DBHOST
              value: http://aivid-node-office1-db-service:9200
            - name: DBCHOST
              value: http://aivid-cloud-gateway-service:8080/cloud/api/db
            - name: STHOST
              value: http://aivid-node-office1-storage-service:8080/api/upload
            - name: STCHOST
              value: http://aivid-cloud-gateway-service:8080/cloud/api/upload
            - name: DBMHOST
              value: http://aivid-node-office1-db-service-metricbeat:9200
            - name: SERVICE_INTERVAL
              value: '30'
            - name: NO_PROXY
              value: '*'
            - name: no_proxy
              value: '*'
          volumeMounts:
            - mountPath: /home/bot
              name: bot
            - mountPath: /home/storage
              name: storage
      volumes:
        - name: bot
          persistentVolumeClaim:
            claimName: office1-tmp
        - name: storage
          persistentVolumeClaim:
            claimName: office1-storage-tmp
